
package PMS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PMSGetStoredServiceService", targetNamespace = "http://service.pms.com/", wsdlLocation = "http://localhost:9001/Service/PMSGetStoredService?wsdl")
public class PMSGetStoredServiceService
    extends Service
{

    private final static URL PMSGETSTOREDSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PMSGETSTOREDSERVICESERVICE_EXCEPTION;
    private final static QName PMSGETSTOREDSERVICESERVICE_QNAME = new QName("http://service.pms.com/", "PMSGetStoredServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9001/Service/PMSGetStoredService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PMSGETSTOREDSERVICESERVICE_WSDL_LOCATION = url;
        PMSGETSTOREDSERVICESERVICE_EXCEPTION = e;
    }

    public PMSGetStoredServiceService() {
        super(__getWsdlLocation(), PMSGETSTOREDSERVICESERVICE_QNAME);
    }

    public PMSGetStoredServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PMSGETSTOREDSERVICESERVICE_QNAME, features);
    }

    public PMSGetStoredServiceService(URL wsdlLocation) {
        super(wsdlLocation, PMSGETSTOREDSERVICESERVICE_QNAME);
    }

    public PMSGetStoredServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PMSGETSTOREDSERVICESERVICE_QNAME, features);
    }

    public PMSGetStoredServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PMSGetStoredServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PMSGetStoredService
     */
    @WebEndpoint(name = "PMSGetStoredServicePort")
    public PMSGetStoredService getPMSGetStoredServicePort() {
        return super.getPort(new QName("http://service.pms.com/", "PMSGetStoredServicePort"), PMSGetStoredService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PMSGetStoredService
     */
    @WebEndpoint(name = "PMSGetStoredServicePort")
    public PMSGetStoredService getPMSGetStoredServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.pms.com/", "PMSGetStoredServicePort"), PMSGetStoredService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PMSGETSTOREDSERVICESERVICE_EXCEPTION!= null) {
            throw PMSGETSTOREDSERVICESERVICE_EXCEPTION;
        }
        return PMSGETSTOREDSERVICESERVICE_WSDL_LOCATION;
    }

}
